"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const notificationController_1 = require("../controllers/notificationController");
const auth_1 = require("../middleware/auth");
const router = (0, express_1.Router)();
router.use(auth_1.authMiddleware);
router.get("/", notificationController_1.getNotifications);
router.patch("/:notificationId/read", notificationController_1.markNotificationRead);
exports.default = router;
